name: Check and Format Code

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check if black has been run
        id: check
        run: |
          black --check src || echo "Black check failed"

  format:
    runs-on: ubuntu-latest
    needs: check-black
    if: failure()
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install black isort autoflake
      - name: Format code with black
        run: |
          black --include="\.py" src
      - name: Sort imports with isort
        run: |
          isort src
      - name: Remove unused imports with autoflake
        run: |
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive src
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Automatic code formatting with black, sort imports with isort, and remove unused imports with autoflake"
          add: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}