name: Concurrency 1
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                type: environment
                required: true
                default: 'main'

concurrency: concurrency-1
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30