# Regardless of the concurrency group, the workflow will run in the same job.
# So, running the workflow with the same environment will cancel the previous run.
# So we need to add a custom workflow name to differentiate the workflow runs.
name: Concurrency 2
run-name: Concurrency 2 (${{ github.event.inputs.environment }})
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                type: environment
                required: true
                default: 'main'

concurrency: 
    # group: concurrency-1
    # group: ${{ github.event.inputs.environment }}
    # giving the group a unique name by combining the workflow name and the environment name or the run id
    group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
    # group: ${{ github.event.inputs.environment }}-${{ github.run_id }}
    # This will cancel the previous run in the same group on the same branch only. So, different branches will not be affected.
    # group: ${{ github.workflow }}-${{ github.ref }}
    # Set to true to cancel any in-progress runs in the same group. This will not cancel the current run.
    cancel-in-progress: true
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30