name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
          image: node:20.3-alpine3.17
        #   If we are using a private Docker registry, we can authenticate with the following credentials:
        #   credentials:
        #     username: ${{ secrets.DOCKER_USERNAME }}
        #     password: ${{ secrets.DOCKER_PASSWORD }}
          env:
            API_URL: https://api.example.com
            ports: 80
            # volumes:
            #     - vol_name: /path/in/container
            #     - /var/lib/data
            #     - /path/in/host:/path/in/container
            # options: --cpus 1 --memory 512m
        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                npm -v
                uname -a
                cat /etc/os-release
            - name: Log Env
              run: |
                echo $API_URL
                echo $ports
            - name: Create a file
              run: echo 'Hello, World!' > hello.txt
            - name: Container in a Step
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node
                # args are used instead of cmd in Dockerfile
                args: -p 2+3
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                # args are used instead of cmd in Dockerfile
                args: -v
            - name: Show file contents
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: hello.txt
            - uses: actions/checkout@v3
            - name: Run a bash script
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: ./script.sh
                args: "Hello, World!"
            - name: Send a Slack notification
              uses: docker://technosophos/slack-notify
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_USERNAME: GitHub Actions Bot
                SLACK_TITLE: "Hello, World!"
                SLACK_MESSAGE: "This is a test message. Actor: ${{ github.actor }}, Repo: ${{ github.repository }}, SHA: ${{ github.sha }}, Ref: ${{ github.ref }}, event: ${{ github.event_name }}"
                SLACK_COLOR: "#723fc4"
                SLACK_ICON: "https://avatars.githubusercontent.com/u/44036562"
                SLACK_CHANNEL: "#fuckin-botches-and-making-money"