
name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        options:
          ubuntu-latest: 'Ubuntu'
          windows-latest: 'Windows'
          macos-latest: 'macOS'
      node-version:
        description: 'Node Version'
        required: true
        default: '14'
        options:
          13: '13'
          14: '14'
          15: '15'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Preparing matrix"
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value 2" >> $GITHUB_OUTPUT
        id: step-2
      - run: |
          echo '${{ steps.step-1.outputs.step-output }}'
          echo '${{ steps.step-2.outputs.step-output }}'

  node-matrix:
      strategy:
          matrix:
              os: [ubuntu-latest, windows-latest]
              node-version: [13, 14, 15]
      runs-on: ${{ matrix.os }}
      steps:
          - run: node -v
          - uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
          - run: node -v
