
name: First Workflow
on: [push]

jobs:
    run-shell-commands:
      runs-on: ubuntu-latest
      steps:
        - name: Run and echo a one-line script
          run: echo "Hello, world!"
        - name: Run and echo a multi-line script
          run: |
            node -v
            npm -v
    
    parallel-job-macOS:
      runs-on: macos-latest
      steps:
        - name: View SW version
          run: sw_vers
    dependent-job:
      runs-on: windows-latest
      needs: [run-shell-commands, parallel-job-macOS]
      steps:
        - name: echo a string
          run: Write-OutPut "Hello, world! as a Windows String"
          