
name: Actions Introduction
on: [push]

jobs:
  first-action-use:
    runs-on: ubuntu-latest
    steps:
      - name: First Action Use
        # This uses the action in the .github/actions/first-action directory
        # uses: .github/actions/first-action@main
        # After the @ symbol, you can specify a branch, tag, or commit SHA
        id: first-action-use
        uses: actions/hello-world-javascript-action@main
        # with keyword is used to pass input to the action
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Log Greeting
        run: echo "The time was '${{ steps.first-action-use.outputs.time }}'"

