# the repo that you are calling must be either public or internal - private repos didn't work for me
name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Vincent'
        required: false
jobs:
#   call-reusable-workflow:
    # Use the workflow name provided in the input
    # make sure that we allow resuable workflows in the organization settings
    # org > settings > actions > general > allow resuable workflows
    # uses: mlops-proving-grounds/reusable-workflow/.github/workflows/reusable.yaml@main  # Replace 'main' with the appropriate branch or tag
    # with:
    #   name: ${{ inputs.name }}
    #   secrets: inherit # this will inherit and give all the secrets from the parent workflow
    #   secrets: 
        # access-token: ${{ secrets.ACCESS_TOKEN }}
  calling-a-reuseable-wf-in-the-same-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
  using-reusable-workflow-output:
    runs-on: ubuntu-latest
    needs: calling-a-reuseable-wf-in-the-same-repo
    steps:
        - run: echo ${{ needs.calling-a-reuseable-wf-in-the-same-repo.outputs.date }}
            