
# You can only have 3 layers of workflows.
name: Workflow Run
on:
    workflow_run:
        workflows: [Repo Events]
        types: [completed]
jobs:
    add-new-comment:
        runs-on: ubuntu-latest
        steps:
            - name: Add a new comment
              uses: actions/github-script@v6
              with:
                
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: 'I am a workflow run, that runs after the Repo Events workflow is completed! byukisha!'
                        })