
# You can only have 3 layers of workflows.
name: Workflow Run
on:
    workflow_run:
        workflows: [Repo Events]
        types: [completed]
jobs:
    add-new-comment:
        runs-on: ubuntu-latest
        steps:
            - name: Add a new comment
              uses: mshick/add-pr-comment@v2
              with:
                message: |
                 "Hello, 
                 world, 
                 bitches!"