
# You can only have 3 layers of workflows.
name: Workflow Run
on:
    workflow_run:
        workflows: [Repo Events]
        types: 
            - completed
jobs:
    echo-new-comment:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is a new comment, because the other code sucks."