
name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semi-colon" 
            - name: Setting a error message with params
              run: echo "::error title:Error title, file=app.js, line=10, endLine=13, col=15, endColumn=21::This is an error message"
            - name: Setting a debug message with params
              run: echo "::debug title:Debug title, file=app.js, line=10, endLine=13, col=15, endColumn=21::This is an debug message"
            - name: Setting a warning message with params
              run: echo "::warning title:Warning title, file=app.js, line=10, endLine=13, col=15, endColumn=21::This is an warning message"
            - name: Setting a notice message with params
              run: echo "::notice title:Notice title, file=app.js, line=10, endLine=13, col=15, endColumn=21::This is an notice message"
            - name: Group of logs
              run: |
                echo "::group::Grouping logs title"
                echo "This is a log message"
                echo "::error title:Error title, file=app.js, line=10, endLine=13, col=15, endColumn=21::This is an error message"
                echo "::notice title:Notice title, file=app.js, line=10, endLine=13, col=15, endColumn=21::This is an notice message"
                echo "This is another log message"
                echo "::endgroup::"
            - name: Masking a value
              run: "::add-mask::my-secret-value"
            - name: echo a secret
              run: echo "my-secret-value"